shoppinglist/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts" 
urlpatterns = [
    path("profile/details", views.profile_details, name="profile_details"),
    path("profile/friends/", views.friends, name="friends"),
    path("profile/friends/<int:id>", views.profile_details, name="profile_details_by_id"),
    path("profile/friends/<str:action>/<int:id>", views.add_delete_friends, name="add_delete_friends"),
    path("profile/edit_profile/", views.edit_profile, name="edit_profile"),
    path("profile/change_password", views.change_password, name="change_password"),
]

shoppinglist/main/urls.py
from django.urls import path

from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'main'
urlpatterns = [
    path("<int:id>", views.list_renderer, name="list_renderer"),
    path("userhome/", views.userhome, name="userhome"),
    path("<int:id>/sortlist/", views.sort_list, name="sortlist"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

shoppinglist/shoppinglist/urls.py
from django.contrib import admin
from django.urls import path, include
from register import views as v
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', v.register, name="register"),
    path('login/', auth_views.LoginView.as_view(redirect_authenticated_user=True), name='login'),
    path('', include("main.urls")),
    path('', include("nouser.urls")),
    path('', include("accounts.urls")),
    path('', include("django.contrib.auth.urls")),
]

shoppinglist/accounts/models.py
from django.db import models


# Create your models here.

shoppinglist/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm


class EditProfileForm(UserChangeForm):
    
    class Meta:
        model = User
        fields = (
            'username',
            'first_name',
            'last_name',
            'email',
        )

shoppinglist/accounts/views.py
from django.shortcuts import render
from main.models import SList, Item, UserProfile, Friend
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
#from django.contrib.auth.forms import UserChangeForm
from . forms import EditProfileForm
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages


@login_required(login_url='login')
def profile_details(response, id=None):
    
    if id:
        user = User.objects.get(id=id)
    else:
        user = response.user
    
    args = {'user':user}
    return render(response, "accounts/profile_details.html", args)


@login_required(login_url='login')    
def friends(response):
    
    users = User.objects.exclude(id=response.user.id)
        
    if response.user.friends.all().exists():
        friends = response.user.friends.get().users.all()
    else:
        friends = [ ]

    #friends = response.user.friends.get().users.all()
    
    args = {'users':users, 'friends':friends}
    return render(response, "accounts/friends.html", args)





@login_required(login_url='login')   
def add_delete_friends(response, action, id):
    new_friend = User.objects.get(id=id)
    if action == 'add':
        Friend.make_friend(response.user, new_friend)
    elif action =='delete':
        Friend.delete_friend(response.user, new_friend)
    return redirect('accounts:friends')


@login_required(login_url='login') 
def edit_profile(response):
    
    if response.method == 'POST':
        form = EditProfileForm(response.POST, instance=response.user)
        
        if form.is_valid():
            form.save()
            messages.success(response, 'Profile details succesfully updated !')
            return redirect('/profile/details')
    else:
        form = EditProfileForm(instance=response.user)
        args = {'form':form}
        return render(response, "accounts/edit_profile.html", args)
        
    # return render(response, "accounts/edit_profile.html", args)


@login_required(login_url='login') 
def change_password(response):
    
    if response.method == 'POST':
        form = PasswordChangeForm(data=response.POST, user=response.user)
        
        if form.is_valid():
            form.save()
            update_session_auth_hash(response, form.user)
            messages.success(response, 'Password succesfully updated !')
            return redirect('/profile/details')
        else:
            messages.error(response, 'Something went wrong. Try again.')
            return redirect("/profile/change_password")
    
    else:
        form = PasswordChangeForm(user=response.user)
        args = {'form':form}
        return render(response, "accounts/change_password.html", args)

shoppinglist/accounts/templates/accounts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <style type="text/css">
      .container {
      
        margin: 4px;
        border: 3px;
        /* border: 3px solid #3fa5db; */
      }
      .row {
        padding: 3px;
        margin: 4px;
        border: 1px;
        /* border: 1px solid #7451EB; */
      }
      .col {
        padding: 1rem;
        margin: 4px;
        border: 3px;
      }

      #cards {
        padding-top: 15px;
        padding-bottom: 15px;
      }
     
      p {
        padding: 1rem;
      }
      h3 {
        padding: 1rem;
      }
      table {
        text-align: center;
        margin-top: 20px;
        
      }
      #first_colum {
        padding-top: 70px;
        padding-bottom: 70px;
      }

    </style>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
      integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous" />    

    <title>{% block title %}Shopping list{% endblock %}</title>

</head>

<body>

    <div class="bg-dark">
      <div class="container">
        <div class="row">

            <nav class="col navbar navbar-expand-lg navbar-dark">
              <a class="navbar-brand" href="/userhome">
                <img src="{% static 'images/banana.png' %}" width="50" height="50" />
                Your lists
              </a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarContent">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item">
                      <a class="nav-link" href="/logout">Logout</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="/profile/details"><h4>{{ user.get_username }}</h4></a>
                    </li>
                </ul>
              </div>
            </nav>

        </div>
      </div>  
    </div>

    <div class="container px-4">
        <div class="row gx-5">
          <div class="col-sm-4" id="first_colum">
            <div class="p-3 border bg-light"> 
              <div class="list-group">
                <a href="/profile/details" class="list-group-item list-group-item-action">
                  Details
                </a>
                <a href="/profile/friends" class="list-group-item list-group-item-action" >Friends</a>
                <a href="/profile/edit_profile" class="list-group-item list-group-item-action">Edit profile</a>
                <a href="/profile/change_password" class="list-group-item list-group-item-action">Change password</a>
              </div>
            </div>
          </div>
          <div class="col-8">
              {% block content %}
              {% endblock %}
          </div>
      </div>
    </div>

    <!-- <div class="footer fixed-bottom bg-light">
      <div class="container">
        <div class="row">
          <div class="col">
            <ul class="list-inline text-center">
              <li class="list-inline-item"><a href="#">About Us</a></li>
              <li class="list-inline-item">&middot;</li>
              <li class="list-inline-item"><a href="#">Privacy</a></li>
              <li class="list-inline-item">&middot;</li>
              <li class="list-inline-item"><a href="">Terms of Use</a></li>
            </ul>
          </div>
        </div>
      </div>    
    </div>  -->
    

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>

</body>

</html>

shoppinglist/accounts/templates/accounts/change_password.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

<title>Change password</title>

{% block title %}Shopping list | change password{% endblock %}

{% block content %}

    {% if user.is_authenticated %}
        
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <div class="container">
        <p><h1>Change password</h1></p>
        <form method="POST" class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-info">Submit</button>
        </form>
    </div>

    {% else %}
        <p>Login <a href="/login">Here</a></p>
    {% endif %}
      
{% endblock %}

shoppinglist/accounts/templates/accounts/edit_profile.html
{% extends 'accounts/base.html' %}
{% load crispy_forms_tags %}

{% block title %}Shopping list | edit profile{% endblock %}

<title>Profile</title>

{% block content %}

    {% if user.is_authenticated %}
        
    <div class="container">
        <p><h1>Edit profile</h1></p>
        <form method="POST" class="form-group">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-info">Submit</button>
        </form>
    </div>

    {% else %}
        <p>Login <a href="/login">Here</a></p>
    {% endif %}
      
{% endblock %}

shoppinglist/accounts/templates/accounts/friends.html
{% extends 'accounts/base.html' %}

{% block title %}Shopping list | friends{% endblock %}

{% block content %}

    {% if user.is_authenticated %}

    <div class="container">
        <p><h1>Friends</h1></p>

        <div class="row">
            {% for friend in friends %}
            <div class="col-sm-6" id="cards">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">
                    <a href="{% url 'accounts:profile_details_by_id' id=friend.id %}">
                    {{friend.username}}
                    </h5></a>
                  <p class="card-text">{{friend.email}}</p>
                  <a class="btn btn-dark" href="{% url 'accounts:add_delete_friends' action='delete' id=friend.id %}" role="button">Delete</a>
                </div>
              </div>
            </div>
            {% endfor %}
        </div>

        <div class="container">
            <p><h1>Community</h1></p>
            {% for user in users %}
                <div class="row g-3">
                    <div class="col-3">
                        <a href="{% url 'accounts:profile_details_by_id' id=user.id %}">
                            <h4>{{user.username}}</h4>
                        </a>
                    </div>
                    <div class="col-3">
                     {% if not user in friends %}
                        <a class="btn btn-light" href="{% url 'accounts:add_delete_friends' action='add' id=user.id %}" role="button">Add</a>
                     {% endif %}
                    </div>
                </div>
            {% endfor %}
  
            
        </div>
       
    </div>

    {% else %}
        <p>Login <a href="/login">Here</a></p>
    {% endif %}
      
{% endblock %}

shoppinglist/accounts/templates/accounts/profile_details.html
{% extends 'accounts/base.html' %}

<title>Profile</title>

{% block title %}Shopping list | profile details{% endblock %}

{% block content %}

    {% if user.is_authenticated %}

        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}

        <div class="container">
            <p><h1>Profile details</h1></p>
            <p>Username: {{user.username}}</p>
            <p>First name: {{user.first_name}}</p>
            <p>Last name: {{user.last_name}}</p>
            <p>Email: {{user.email}}</p>
            <!-- <p>Creation date: {{user.userprofile.date_created}}</p> -->
        </div>

    {% else %}
        <p>Login <a href="/login">Here</a></p>
    {% endif %}
      
{% endblock %}